master:
  image: salt-master
  ports:
    - 4505:4505
    - 4506:4506
    - 8000
  hostname: salt
  volumes:
    - /srv/salt:/srv/salt
  environment:
    - MASTER=True
  command: saltcmd

minion:
  image: salt-minion
  links:
    - master:salt
  environment:
    - MINION=True
  command: saltcmd
